name: geo_catatan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Paket modul
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

  # Tambahan untuk tugas mandiri
  google_maps_flutter: ^2.5.0
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/rumah.png
    - assets/icons/toko.png
    - assets/icons/kantor.png
